DROP TABLE IF EXISTS users_chats_roles CASCADE;

CREATE TABLE users_chats_roles(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(google_sub) ON DELETE CASCADE,
    chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    role VARCHAR(10) NOT NULL CHECK (role IN ('USER','ADMIN','MODERATOR'))
)